FROM broadcptacdev/panoply_common:latest

LABEL maintainer="karsten@broadinstitute.org"
LABEL description="Docker for single-omics kmeans consensus clustering."


MAINTAINER rkothadi@broadinstitute.org


COPY src /prot/proteomics/Projects/PGDAC/src
