FROM broadcptacdev/panoply_common:latest

LABEL maintainer="proteogenomics@broadinstitute.org"
LABEL description="Docker for single-omics kmeans consensus clustering."


MAINTAINER proteogenomics@broadinstitute.org


COPY src /prot/proteomics/Projects/PGDAC/src
