FROM broadcptacdev/panoply_common:74e21ac

LABEL maintainer="karsten@broadinstitute.org"
LABEL description="Docker for single-omics kmeans consensus clustering."

RUN rm -R /prot/proteomics/Projects/PGDAC/src/*
COPY src/* /prot/proteomics/Projects/PGDAC/src/
