FROM broadcptacdev/panoply_libs:latest
MAINTAINER proteogenomics@broadinstitute.org

COPY R-utilities/ /prot/proteomics/Projects/R-utilities

RUN wget -P /prot/proteomics/Projects/Protigy/ https://raw.githubusercontent.com/broadinstitute/protigy/master/src/modT.R 