FROM broadcptac/pgdac_rmd:2

LABEL maintainer="karsten@broadinstitute.org"
LABEL description="Docker for generating Rmarkdown reports for different PGDAC modules."

ENV wd /home/pgdac/

COPY . $wd
WORKDIR $wd
