FROM broadcptacdev/panoply_rmd_report:latest

LABEL maintainer="proteogenomics@broadinstitute.org"
LABEL description="Docker for generating Rmarkdown reports for different PGDAC modules."

ENV wd /prot/proteomics/Projects/PGDAC/src

COPY src /prot/proteomics/Projects/PGDAC/src
WORKDIR $wd