---
output:
  html_document:
    toc: yes
    toc_float:
      smooth_scroll: no
params:
  title: "Single -Ome NMF Comparisons"
  sankey_tar: NULL
  so_nmf_tar: NULL
  mo_nmf_tar: NULL
  label: NULL
---

---
title: `r params$title`
---

```{r setup, include=FALSE}
library(htmltools)
library(stringr)
library(glue)

```

This document visualizes and compares NMF clustering results, when based on features from single-omes.

# Sankey Diagrams

```{r sankey_diagrams, results='asis', echo=FALSE, out.width='100%', out.height='50%'}

untar(params$sankey_tar)
sankey_files = list.files(pattern="sankey.+html")

ome_types = str_split(sankey_files, '_', simplify=TRUE)[,1] %>% str_replace(., 'sankey-', "") %>% unique()

if ("Multiomic" %in% ome_types) { #if we analyzed multiomic data
  ome_types = c("Multiomic", ome_types[which(ome_types!="Multiomic")]) #move Multiomics to front of ome_types vector
}

for(ome in ome_types) {
  cat("  \n## ",  ome, " {.tabset}  \n")
  
  files_tmp = list.files(pattern=glue("sankey-{ome}.+Source.html"))
  files_tmp = files_tmp[grep("_Multiomic_", files_tmp, invert = TRUE)] #only plot figures that DON'T have MO-NMF in the center
  
  if ("Multiomic" %in% ome_types) { #if we analyzed multiomic data
    mo_sankey = grep("Multiomic", files_tmp, value=TRUE)
    files_tmp = c(mo_sankey, files_tmp[which(files_tmp!=mo_sankey)]) #move Multiomics sankey file to front of files_tmp vector
  }
  
  for(file in files_tmp) {
    other_ome = str_replace(file, glue("sankey-{ome}_"), "") %>% str_replace(., '-.+html', '')
    cat("  \n### ",  other_ome, " \n")
    # include Sankey Diagrams
    print(htmltools::tagList(tags$iframe(srcdoc=includeHTML(file), seamless="seamless", frameBorder = 0, height="400vh", width="100%")))
    cat("  \n")
    cat(glue("**{ome} vs {other_ome}** This sankey diagram compares the results clustering when using {ome} features, to clustering when using {other_ome} features."))
    cat("  \n")
  }
}

```




