FROM broadcptacdev/panoply_rmd_report:latest

LABEL maintainer="karsten@broadinstitute.org"
LABEL description="Docker for generating Rmarkdown reports for different PANOPLY's CNA correlation module."

ENV wd /home/pgdac/

COPY . $wd
WORKDIR $wd
