FROM broadcptac/pgdac_ssgsea:4

LABEL maintainer="karsten@broadinstitute.org"
LABEL description="Docker running gene-centric single-sample Gene Set Enrichment Analysis (ssGSEA) and PTM Signature Enrichment Analysis (PTM-SEA)".

ENV wd /home/pgdac/

COPY . $wd
#COPY src src/

WORKDIR $wd

## install R-packages
RUN R -e "install.packages('pacman')"
RUN R -e "library(pacman);p_install('glue')"
RUN R -e "library(pacman);p_install('dplyr')"
RUN R -e "library(pacman);p_install('RSQLite')"
RUN R -e "library(pacman);p_install('org.Hs.eg.db')"
RUN R -e "library(pacman);p_install('org.Mm.eg.db')"
RUN R -e "library(pacman);p_install('org.Rn.eg.db')"
RUN R -e "library(pacman);p_install('org.Dr.eg.db')"










