FROM broadcptac/pgdac_mo_nmf:3

LABEL maintainer="karsten@broadinstitute.org"
LABEL description="Docker for multi-omic NMF clustering."

ENV wd /home/pgdac/

COPY . $wd

WORKDIR $wd

RUN R -e "library(pacman);p_install('UpSetR')"
RUN R -e "library(pacman);p_install('ComplexHeatmap')"
