FROM rocker/r-ver:3.4
#FROM broadcptac/r-util:1
#FROM r-base
#FROM broadcptac/pgdac_ssgsea:3

LABEL maintainer="karsten@broadinstitute.org"
LABEL description="Docker for multi-omic NMF clustering."

ENV wd /home/pgdac/

COPY . $wd
#COPY src src/

WORKDIR $wd

RUN apt-get update
#RUN apt-get install -y apt-utils
## required for R-pacakge 'XML'
#RUN apt-get -t unstable install -y libxml2-dev
RUN apt-get install -y libxml2-dev

## rmarkdown
RUN apt-get install -y libc6-dev
RUN apt-get install -y perl
#RUN apt-get -t unstable install -y pandoc
RUN apt-get install -y pandoc

## ssl
RUN apt-get install -y libssl-dev
## libcurl
RUN apt-get install -y libcurl4-openssl-dev


## install R-packages
RUN R -e "install.packages('pacman')"

RUN R -e "install.packages('pacman')"
RUN R -e "library(pacman);p_install('stringi')"
RUN R -e "library(pacman);p_install('pkgmaker')"
RUN R -e "library(pacman);p_install('reshape2')"
RUN R -e "library(pacman);p_install('ggplot2')"
RUN R -e "library(pacman);p_install('rngtools')"
RUN R -e "library(pacman);p_install('NMF')"

RUN R -e "library(pacman);p_install('IRanges')"
RUN R -e "library(pacman);p_install('S4Vectors')"
RUN R -e "library(pacman);p_install('annotationDbi')"
RUN R -e "library(pacman);p_install('org.Hs.eg.db')"
Run R -e "library(pacman);p_install('rhdf5')"
RUN R -e "devtools::install_github('cmap/cmapR')"
RUN R -e "library(pacman);p_install('optparse')"
RUN R -e "library(pacman);p_install('verification')"
RUN R -e "library(pacman);p_install('gtools')"
RUN R -e "library(pacman);p_install('foreach')"
RUN R -e "library(pacman);p_install('doParallel')"
RUN R -e "library(pacman);p_install('magrittr')"

RUN R -e "library(pacman);p_install('maptools')"
RUN R -e "library(pacman);p_install('pheatmap')"
RUN R -e "library(pacman);p_install('WriteXLS')"
RUN R -e "library(pacman);p_install('RColorBrewer')"

RUN R -e "library(pacman);p_install('glue')"
RUN R -e "library(pacman);p_install('tidyselect')"
RUN R -e "library(pacman);p_install('dplyr')"

RUN R -e "library(pacman);p_install('Rtsne')"
RUN R -e "library(pacman);p_install('plotly')"
RUN R -e "library(pacman);p_install('rmarkdown')"
RUN R -e "library(pacman);p_install('vioplot')"

# v2: FROM broadcptac/pgdac_mo_nmf:3
RUN R -e "library(pacman);p_install('UpSetR')"
RUN R -e "library(pacman);p_install('ComplexHeatmap')"

# v3: FROM broadcptac/pgdac_mo_nmf:4
RUN R -e "library(pacman);p_install('impute')"

# v4: FROM broadcptac/pgdac_mo_nmf:5
RUN R -e "library(pacman);p_install('doParallel')"
RUN R -e "library(pacman);p_install('foreach')"
RUN R -e "library(pacman);p_install('readxl')"
RUN R -e "library(pacman);p_install('ccfindR')"

# v5: FROM broadcptac/pgdac_mo_nmf:6
RUN R -e "library(pacman);p_install('tibble')"
#RUN R -e "library(pacman);p_install('magrittr')"

# v6: FROM broadcptac/pgdac_mo_nmf:5
#RUN R -e "library(pacman);p_install('doParallel')"
#RUN R -e "library(pacman);p_install('foreach')"
#RUN R -e "library(pacman);p_install('readxl')"
#RUN R -e "library(pacman);p_install('ccfindR')"

#RUN R -e "library(pacman);p_install('tibble')"
#RUN R -e "library(pacman);p_install('magrittr')"

# v7-v10: updates to R-code

# v11: FROM broadcptac/pgdac_mo_nmf:10
RUN R -e "library(pacman);p_install('limma')"
RUN R -e "pacman::p_install('statmod')"
RUN R -e "pacman::p_install('BiocManager')"

## update ComplexHeatmap
RUN wget https://bioconductor.org/packages/release/bioc/src/contrib/ComplexHeatmap_2.2.0.tar.gz
RUN R -e "pacman::p_install(c(clue, png))"
RUN R -e "install.packages('circlize')"
RUN R -e "install.packages('ComplexHeatmap_2.2.0.tar.gz', repos = NULL, type='source')"

# v12: FROM broadcptac/pgdac_mo_nmf:11
RUN R -e "pacman::p_install('ggpubr')"

# v13: FROM broadcptac/pgdac_mo_nmf:12
RUN R -e "pacman::p_install('yaml')"