FROM broadcptacdev/panoply_rmd_report:latest

LABEL maintainer="proteogenomics@broadinstitute.org"
LABEL description="Docker for generating Rmarkdown reports for different PGDAC modules."

ENV wd /home/pgdac/

COPY . $wd
WORKDIR $wd
